// auto generated by go tool dist

package sys

const DefaultGoroot = `/home/ernest/working/devel/go-linux-arm64-bootstrap`
const TheVersion = `devel +ed915ad Fri Sep 23 04:32:38 2016 +0000`
const Goexperiment = ``
const StackGuardMultiplier = 1

